# Generated by Django 3.0.3 on 2020-04-14 12:36

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_active', models.BooleanField(default=False)),
                ('tag_name', models.CharField(db_index=True, max_length=100)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Article',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_active', models.BooleanField(default=False)),
                ('article_name', models.CharField(max_length=100, null=True)),
                ('article_text', models.CharField(max_length=1000, null=True)),
                ('article_date', models.DateTimeField(default=datetime.datetime(2020, 4, 14, 12, 36, 47, 212381))),
                ('article_rating', models.IntegerField(null=True)),
                ('article_img', models.ImageField(blank=True, null=True, upload_to='articles')),
                ('article_tag', models.ManyToManyField(to='articles.Tag')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
